/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as TrabalhosRouteImport } from './routes/trabalhos'
import { Route as DocumentosIdRouteImport } from './routes/documentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosRoute = TrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosIdRoute = DocumentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRoute
  '/trabalhos': typeof TrabalhosRoute
  '/documentos/$id': typeof DocumentosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRoute
  '/trabalhos': typeof TrabalhosRoute
  '/documentos/$id': typeof DocumentosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financas': typeof FinancasRoute
  '/trabalhos': typeof TrabalhosRoute
  '/documentos/$id': typeof DocumentosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/diagnostico'
    | '/documentos'
    | '/empresa'
    | '/financas'
    | '/trabalhos'
    | '/documentos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/diagnostico'
    | '/documentos'
    | '/empresa'
    | '/financas'
    | '/trabalhos'
    | '/documentos/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clientes'
    | '/diagnostico'
    | '/documentos'
    | '/empresa'
    | '/financas'
    | '/trabalhos'
    | '/documentos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DocumentosRoute: typeof DocumentosRouteWithChildren
  EmpresaRoute: typeof EmpresaRoute
  FinancasRoute: typeof FinancasRoute
  TrabalhosRoute: typeof TrabalhosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos': {
      id: '/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof TrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos/$id': {
      id: '/documentos/$id'
      path: '/$id'
      fullPath: '/documentos/$id'
      preLoaderRoute: typeof DocumentosIdRouteImport
      parentRoute: typeof DocumentosRoute
    }
  }
}

interface DocumentosRouteChildren {
  DocumentosIdRoute: typeof DocumentosIdRoute
}

const DocumentosRouteChildren: DocumentosRouteChildren = {
  DocumentosIdRoute: DocumentosIdRoute,
}

const DocumentosRouteWithChildren = DocumentosRoute._addFileChildren(
  DocumentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DocumentosRoute: DocumentosRouteWithChildren,
  EmpresaRoute: EmpresaRoute,
  FinancasRoute: FinancasRoute,
  TrabalhosRoute: TrabalhosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
